### ISSUE TITLE
Add R2API as dependency

### ISSUE THREAD

**Issue by david1hung** [wildbook/R2Mods#19]
When launching the game, the mod console says TooManyFriends requires R2API. Should add it to the dependency list so the mod manger can install it automatically.

**Comment by wildbook** [comment]
Hadn't thought of that, thanks! The current release of TMF is from a year or so ago, before R2API was a separate dependency you could add in. I'll try to remember adding it in when I next touch the mod (or have some time left over) and leave the issue open until then.

**Comment by wildbook** [comment]
Should be fixed now.

**Comment by DetachHead** [comment]
i think this is still an issue. the friends i'm playing with hadto manually install R2API
